name: CI

on:
  push:
    branches:
      - main # 触发条件：当代码推送到 main 分支时
  pull_request:
    branches:
      - main # 触发条件：当有 PR 请求合并到 main 分支时

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 镜像

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 检出代码

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.4' # 设置 Node.js 版本

      - name: Install dependencies
        run: npm install # 安装依赖

      - name: Build
        run: npm run build # 编译项目

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts # 上传的产物名称
          path: dist/ # 需要上传的目录，请根据您项目的实际输出目录修改（例如 dist/ 或 out/）
